import os
import requests


LLAMA_BASE_URL = os.getenv(
    "LLAMA_BASE_URL",
    "http://127.0.0.1:11434"
)

LLAMA_MODEL = os.getenv(
    "LLAMA_MODEL",
    "llama3.2:3b"
)


SYSTEM_PROMPT = """
You are the conversational and explanation layer of a mental health
monitoring system.

Your job is to explain AI-generated emotion and distress results in
simple, supportive, non-diagnostic language.

Rules:
- Do not diagnose any mental health condition.
- Do not claim certainty about a person's mental health.
- Do not calculate or invent distress scores.
- Do not change the risk level provided by the prediction model.
- Do not replace the ML prediction models.
- Treat emotion and distress scores as model outputs, not medical facts.
- Be supportive and empathetic.
- Encourage appropriate human support when relevant.
- Keep responses concise and understandable.
"""


def generate_explanation(
    emotions: dict,
    distress_score: float | None = None,
    risk_level: str | None = None
):

    emotion_text = ", ".join(
        f"{emotion}={score:.2f}"
        for emotion, score in emotions.items()
    )

    prompt = f"""
Explain the following AI-generated assessment results
in a supportive, non-diagnostic way.

Emotion results:
{emotion_text}
"""

    if distress_score is not None:
        prompt += f"""
Distress score generated by the prediction model:
{distress_score}
"""

    if risk_level is not None:
        prompt += f"""
Risk level generated by the prediction model:
{risk_level}
"""

    prompt += """
Do not diagnose the person.
Do not change or reinterpret the provided numerical prediction.
Explain what the results may indicate in simple language.
"""

    response = requests.post(
        f"{LLAMA_BASE_URL}/api/generate",
        json={
            "model": LLAMA_MODEL,
            "system": SYSTEM_PROMPT,
            "prompt": prompt,
            "stream": False
        },
        timeout=120
    )

    response.raise_for_status()

    data = response.json()

    return data["response"].strip()